# Generated by Django 4.1.4 on 2022-12-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_porta', '0002_proyectos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proyectos',
            table='Proyectos',
        ),
    ]
